# Generated by Django 6.0.3 on 2026-03-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='code_plain',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
