# Generated by Django 6.0.3 on 2026-03-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usersession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitysettings',
            name='max_sessions',
        ),
        migrations.RemoveField(
            model_name='securitysettings',
            name='session_timeout_minutes',
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='absolute_session_timeout_minutes',
            field=models.PositiveIntegerField(default=10080, help_text='Tempo máximo absoluto da sessão'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='idle_session_timeout_minutes',
            field=models.PositiveIntegerField(default=1440, help_text='Tempo máximo de inatividade da sessão'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='max_devices',
            field=models.PositiveSmallIntegerField(default=3, help_text='Máximo de dispositivos simultâneos permitidos'),
        ),
    ]
