# Generated by Django 6.0.3 on 2026-03-08 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_securitysettings_max_sessions_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='securitysettings',
            name='security_se_user_id_99f42e_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='authenticat_user_id_f427c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='authenticat_user_id_10cb77_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='authenticat_device__c00811_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='authenticat_token_j_80db20_idx',
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='max_sessions_per_device',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='securitysettings',
            name='absolute_session_timeout_minutes',
            field=models.PositiveIntegerField(default=10080),
        ),
        migrations.AlterField(
            model_name='securitysettings',
            name='idle_session_timeout_minutes',
            field=models.PositiveIntegerField(default=1440),
        ),
        migrations.AlterField(
            model_name='securitysettings',
            name='max_devices',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_hash',
            field=models.CharField(db_index=True, default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='token_jti',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='securitysettings',
            name='email_alerts',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='asn',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='proxy',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='tor',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='vpn',
        ),
    ]
