# Generated by Django 6.0.3 on 2026-03-10 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ConsentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('document_hash', models.CharField(editable=False, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='consents.consentterm')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('term', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('document_hash', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('country', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('asn', models.CharField(max_length=50)),
                ('isp', models.CharField(max_length=120)),
                ('is_proxy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consents.consentterm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consents.consentversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'version')},
            },
        ),
    ]
